### PR TITLE
Feature/private event logic

### PR DESCRIPTION
**Pull request by temesghentekeste**
Greetings from Temesghen,

I start to develop the project by creating a repository named private-event-logic. I followed git-flow as git workflow and used Rubocop and Stylelint as linter tools. Devise gem is used to create the authentication feature of the project, and to style the views, Bootstrap is used. Besides, Kaminari gem is used to paginate the posts listing page. To perform different kinds of tests, I use RSpec, Capybara, and other supplementary gems.

Kindly request a pull request before I merge my feature branch to the develop branch.

Regards,
Temesghen T.

### CODE REVIEW

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED ♻️ 

A great effort in this project! 💯 
I am impressed, looks amazing! 👏 🥇 
However, we still need to do a couple of small changes in order to get the project approved 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 
Good luck, and congratulations on this project, it is by far the best one I have reviewed! 😃 
## Mandatory changes
- Remove all commented out code(events controller and event attendances controller)
- Your show action in your users controller should look like this:
* [ ] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- At your events form partial you have a typo(label instead of label)

**Comment by temesghentekeste** [comment]
Thanks :pray: @javitocor for your constructive feedback; I have addressed the issues as per your suggestions; however, as for listing the user upcoming, past, and created events, I have already done them using partials and helpers. Kindly follow the following link provided in the image given below to look at them.

tse-issues

A typical code segment I use inside views/users folder is '_user_past_events.html.erb', a view partial, which is shown below:

some_codes

Thanks.

**Review by SpaYco — APPROVED** [review]
# Project Approved

thank you for making the required changes, your project is now approved!

## Optional

- [ ] Instead of doing stuff like `@user.attended_events.upcoming` inside views, you can instead add a variable `@events` inside the controller and use _that_ instead

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by temesghentekeste** [comment]
Thanks @Spayco for approving the project.

**Pull request merged**
